# Generated by Django 5.2.1 on 2025-05-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Expired', 'Expired')], default='Draft', max_length=20)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(help_text='Brief summary shown in the job list', max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('VIC', 'VIC'), ('NSW', 'NSW'), ('ACT', 'ACT'), ('QLD', 'QLD'), ('NT', 'NT'), ('WA', 'WA'), ('SA', 'SA'), ('Brisbane', 'Brisbane'), ('Canberra', 'Canberra'), ('Remote', 'Remote')], default='ACT', max_length=50)),
                ('job_type', models.CharField(choices=[('Contract', 'Contract'), ('Permanent', 'Permanent'), ('Part-time', 'Part-time'), ('Casual', 'Casual'), ('ICT', 'ICT'), ('Engineering', 'Engineering'), ('Management', 'Management'), ('Accounting', 'Accounting')], default='Contract', max_length=50)),
                ('salary', models.CharField(default='Negotiable', max_length=100)),
                ('clearance', models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Baseline', 'Baseline'), ('NV1', 'NV1'), ('NV2', 'NV2'), ('PV', 'PV')], default='None', max_length=20)),
                ('skills_sets', models.TextField(blank=True, null=True)),
                ('skills_levels', models.CharField(blank=True, max_length=100, null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('current_clearance', models.CharField(max_length=200, verbose_name='Current Level of Defence Clearance')),
                ('clearance_expiry_date', models.DateField(blank=True, null=True, verbose_name='Defence Clearance Expiry Date')),
                ('clearance_number', models.CharField(blank=True, max_length=200, verbose_name='AGVSA CS Number')),
                ('location_of_residence', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('earliest_start_date', models.DateField(blank=True, null=True, verbose_name='Earliest Start Date')),
                ('proposed_rate', models.CharField(blank=True, max_length=200, verbose_name='Proposed Contract Rate')),
                ('proposed_salary', models.CharField(blank=True, max_length=200, verbose_name='Proposed Annual Salary')),
                ('planned_leave', models.CharField(blank=True, max_length=200, verbose_name='Any Planned Leave')),
                ('available_for_interview', models.CharField(default='Yes', max_length=200)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Interviewed', 'Interviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number_of_positions', models.PositiveIntegerField(default=1)),
                ('is_filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RFQTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfqts_no', models.CharField(default='RFQ-0000', max_length=200)),
                ('department', models.CharField(default='General', max_length=200)),
                ('group', models.CharField(default='Default Group', max_length=200)),
                ('directorate', models.CharField(default='Default Directorate', max_length=200)),
                ('project_section', models.CharField(default='Default Project Section', max_length=200)),
                ('task_title', models.CharField(default='Default Task Title', max_length=200)),
                ('commencement_date_for_task', models.DateField(blank=True, null=True)),
                ('completion_date_for_task', models.DateField(blank=True, null=True)),
                ('rfqts_type', models.CharField(default='General', max_length=200)),
                ('closing_date_for_quotation', models.DateField(blank=True, null=True)),
                ('skills_sets', models.TextField(default='Default Skills Set')),
                ('skills_levels', models.CharField(default='Entry Level', max_length=200)),
                ('service_category', models.CharField(default='Default Service Category', max_length=200)),
                ('scope_of_task', models.TextField(default='Default Scope')),
                ('location', models.CharField(default='ACT', max_length=50)),
                ('deliverables', models.TextField(default='Default Deliverables')),
                ('specified_personnel', models.TextField(default='Not Specified')),
                ('evaluation_criteria', models.TextField(default='evaluate')),
                ('applicable_standards_or_references', models.TextField(default='None')),
                ('allowances_or_disbursements', models.TextField(default='None')),
                ('other_relevant_information_or_special_requirements', models.TextField(default='None')),
                ('special_conditions', models.TextField(default='None')),
                ('extension_options', models.TextField(default='None')),
                ('security_clearances_required_for_personnel', models.TextField(default='None')),
                ('quote_form_type', models.CharField(default='Standard', max_length=200)),
                ('rfq_file', models.FileField(blank=True, null=True, upload_to='rfq_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Request for Quotation and Tasking Statement',
                'verbose_name_plural': 'Request for Quotation and Tasking Statements',
            },
        ),
    ]
