# Generated by Django 5.2.1 on 2025-06-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqts',
            name='task_title',
            field=models.CharField(default='Default Task Title', max_length=500),
        ),
    ]
