# Generated by Django 4.2.17 on 2025-05-27 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meets_all_requirements', models.BooleanField(default=False)),
                ('technical_capability', models.BooleanField(default=False)),
                ('technical_details', models.TextField()),
                ('resource_availability', models.BooleanField(default=False)),
                ('resource_details', models.TextField()),
                ('can_meet_timeline', models.BooleanField(default=False)),
                ('timeline_details', models.TextField()),
                ('security_clearance_compliance', models.BooleanField(default=False)),
                ('security_details', models.TextField()),
                ('quality_standards_compliance', models.BooleanField(default=False)),
                ('quality_details', models.TextField()),
                ('additional_compliance_items', models.JSONField(blank=True, default=dict)),
                ('compliance_documents', models.FileField(blank=True, null=True, upload_to='compliance_documents/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('abn', models.CharField(max_length=20, verbose_name='ABN')),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('conflict_of_interest', models.BooleanField(default=False)),
                ('conflict_details', models.TextField(blank=True, null=True)),
                ('confidentiality_agreement', models.BooleanField(default=False)),
                ('insurance_coverage', models.BooleanField(default=False)),
                ('iso_certified', models.BooleanField(default=False)),
                ('iso_certification_details', models.TextField(blank=True, null=True)),
                ('authorized_signatory', models.CharField(max_length=200)),
                ('signatory_position', models.CharField(max_length=200)),
                ('declaration_date', models.DateField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rfqts',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request for Quotation and Tasking Statement', 'verbose_name_plural': 'Request for Quotation and Tasking Statements'},
        ),
        migrations.AddField(
            model_name='rfqts',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_rfqts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfqts',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Closed', 'Closed'), ('Awarded', 'Awarded'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='allowances_or_disbursements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='applicable_standards_or_references',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='closing_date_for_quotation',
            field=models.DateField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='commencement_date_for_task',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='completion_date_for_task',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='deliverables',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='directorate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='evaluation_criteria',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='extension_options',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='group',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='other_relevant_information_or_special_requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='project_section',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='quote_form_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='rfqts_no',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='rfqts_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='scope_of_task',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='security_clearances_required_for_personnel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='service_category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='skills_levels',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='skills_sets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='special_conditions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='specified_personnel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='task_title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='QuoteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quote_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_inclusive', models.BooleanField(default=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proposed_resources', models.JSONField(default=list)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('deliverables_breakdown', models.TextField()),
                ('payment_terms', models.CharField(max_length=200)),
                ('validity_period', models.IntegerField(help_text='Quote validity in days')),
                ('assumptions', models.TextField(blank=True, null=True)),
                ('exclusions', models.TextField(blank=True, null=True)),
                ('quote_document', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='quote_supporting/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_form', to='jobs.complianceform')),
                ('declaration_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_form', to='jobs.declarationform')),
                ('rfqts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_forms', to='jobs.rfqts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rfqts', 'user')},
            },
        ),
        migrations.AddField(
            model_name='declarationform',
            name='rfqts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_forms', to='jobs.rfqts'),
        ),
        migrations.AddField(
            model_name='declarationform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('template_version', models.CharField(max_length=20)),
                ('cost_categories', models.JSONField(default=dict)),
                ('price_weight', models.IntegerField(default=40)),
                ('technical_weight', models.IntegerField(default=30)),
                ('experience_weight', models.IntegerField(default=20)),
                ('compliance_weight', models.IntegerField(default=10)),
                ('template_file', models.FileField(upload_to='costing_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfqts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing_sheet', to='jobs.rfqts')),
            ],
        ),
        migrations.AddField(
            model_name='complianceform',
            name='declaration_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_form', to='jobs.declarationform'),
        ),
        migrations.AddField(
            model_name='complianceform',
            name='rfqts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_forms', to='jobs.rfqts'),
        ),
        migrations.AddField(
            model_name='complianceform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='awarded_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_job', to='jobs.quoteform'),
        ),
        migrations.AlterUniqueTogether(
            name='declarationform',
            unique_together={('rfqts', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='complianceform',
            unique_together={('rfqts', 'user')},
        ),
    ]
