# Generated by Django 5.2.1 on 2025-06-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_rfqts_task_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQTSFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RFQTS Field Mapping Template',
                'verbose_name_plural': 'RFQTS Field Mapping Templates',
            },
        ),
        migrations.AddField(
            model_name='rfqts',
            name='date_rfqts_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfqts',
            name='key_result_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rfqts',
            name='max_cvs',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rfqts',
            name='max_rate_per_day',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rfqts',
            name='security_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rfqts',
            name='statement_of_duties',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rfqts',
            name='location',
            field=models.CharField(default='ACT', max_length=255),
        ),
        migrations.AddField(
            model_name='rfqts',
            name='field_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.rfqtsfieldmapping'),
        ),
        migrations.CreateModel(
            name='RFQTSField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Model field name (e.g., 'rfqts_no')", max_length=100)),
                ('display_name', models.CharField(help_text='Display name for admin', max_length=200)),
                ('pdf_label', models.CharField(help_text="Label to search for in PDF (e.g., 'RFQTS Number:')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('decimal', 'Decimal'), ('multiline', 'Multi-line Text'), ('table', 'Table')], default='text', max_length=20)),
                ('extract_until', models.CharField(blank=True, help_text='Stop extraction at this label/pattern', max_length=200)),
                ('extraction_pattern', models.TextField(blank=True, help_text='Custom regex pattern for extraction')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('mapping_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='jobs.rfqtsfieldmapping')),
            ],
            options={
                'ordering': ['order', 'field_name'],
                'unique_together': {('mapping_template', 'field_name')},
            },
        ),
    ]
