# Generated by Django 5.2.1 on 2025-06-11 02:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rfqtsfieldmapping_rfqts_date_rfqts_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('questions', models.JSONField(default=list, help_text='List of custom questions for risk assessment', verbose_name='Questions Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment Question Template',
                'verbose_name_plural': 'Assessment Question Templates',
            },
        ),
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='costing', serialize=False, to='jobs.jobapplication')),
                ('base_daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base daily rate excluding GST', max_digits=10, verbose_name='Base Daily Rate (ex GST)')),
                ('payroll_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('4.85'), help_text='Payroll tax percentage (editable by management)', max_digits=5, verbose_name='Payroll Tax Rate (%)')),
                ('default_margin_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Default margin percentage', max_digits=5, verbose_name='Default Margin Rate (%)')),
                ('custom_margin_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Custom margin rate (overrides default if set)', max_digits=5, null=True, verbose_name='Custom Margin Rate (%)')),
                ('superannuation_rate', models.DecimalField(decimal_places=2, default=Decimal('11.00'), help_text='Superannuation percentage', max_digits=5, verbose_name='Superannuation Rate (%)')),
                ('workers_comp_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Workers compensation percentage', max_digits=5, verbose_name='Workers Compensation Rate (%)')),
                ('public_liability_cost', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Daily public liability insurance cost', max_digits=8, verbose_name='Public Liability Insurance (per day)')),
                ('gross_daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated gross rate', max_digits=12, null=True, verbose_name='Gross Daily Rate')),
                ('client_charge_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Final rate charged to client including GST', max_digits=12, null=True, verbose_name='Client Charge Rate (inc GST)')),
                ('estimated_days', models.PositiveIntegerField(default=1, help_text='Estimated project duration in days', verbose_name='Estimated Days')),
                ('total_project_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total project cost including all factors', max_digits=15, null=True, verbose_name='Total Project Cost')),
                ('manual_override', models.BooleanField(default=False, help_text='Check to prevent auto-calculation', verbose_name='Manual Override')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about costing decisions', verbose_name='Costing Notes')),
                ('calculated_by', models.ForeignKey(blank=True, help_text='Last user to update calculations', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Costing Sheet',
                'verbose_name_plural': 'Costing Sheets',
            },
        ),
        migrations.CreateModel(
            name='PreSubmissionAssessment',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='risk_assessment', serialize=False, to='jobs.jobapplication')),
                ('all_responses_checked', models.BooleanField(default=False, verbose_name='All candidate responses have been checked and verified')),
                ('clearance_verified', models.BooleanField(default=False, verbose_name='Security clearance requirements verified')),
                ('cv_reviewed', models.BooleanField(default=False, verbose_name='CV reviewed for gaps and accuracy')),
                ('references_contacted', models.BooleanField(default=False, verbose_name='References have been contacted (if required)')),
                ('costing_approved', models.BooleanField(default=False, verbose_name='Costing has been reviewed and approved')),
                ('conflict_assessed', models.BooleanField(default=False, verbose_name='Conflict of interest assessment completed')),
                ('waiver_processed', models.BooleanField(default=False, verbose_name='APS/SERCAT waiver processed (if applicable)')),
                ('client_requirements_met', models.BooleanField(default=False, verbose_name='All client requirements have been confirmed as met')),
                ('custom_assessment_data', models.JSONField(blank=True, default=dict, help_text='Additional configurable assessment questions', verbose_name='Custom Assessment Questions')),
                ('overall_risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], default='Medium', max_length=20, verbose_name='Overall Risk Level')),
                ('ready_for_submission', models.BooleanField(default=False, help_text='Check when application is ready to submit to client', verbose_name='Ready for Submission')),
                ('risk_notes', models.TextField(blank=True, help_text='Additional notes about risks and mitigation strategies', verbose_name='Risk Assessment Notes')),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('submitted_to_client', models.BooleanField(default=False, verbose_name='Submitted to Client')),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name='Submission Date')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-Submission Risk Assessment',
                'verbose_name_plural': 'Pre-Submission Risk Assessments',
            },
        ),
    ]
