# Generated by Django 5.2.1 on 2025-06-11 03:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_assessmentquestiontemplate_costingsheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('Tasmania', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], max_length=20, unique=True, verbose_name='State/Territory')),
                ('rate_percentage', models.DecimalField(decimal_places=2, help_text='Payroll tax rate for this state/territory', max_digits=5, verbose_name='Payroll Tax Rate (%)')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='Effective From')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Tax Rate',
                'verbose_name_plural': 'Payroll Tax Rates',
                'ordering': ['state'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., SME Gateway, ServeGate, Jigsaw', max_length=100, unique=True, verbose_name='Provider Name')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Management fee percentage', max_digits=5, verbose_name='Fee Percentage (%)')),
                ('fee_fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed fee amount (if applicable)', max_digits=10, verbose_name='Fixed Fee Amount ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('VIC', 'VIC'), ('NSW', 'NSW'), ('ACT', 'ACT'), ('QLD', 'QLD'), ('NT', 'NT'), ('WA', 'WA'), ('SA', 'SA'), ('Tasmania', 'Tasmania'), ('Brisbane', 'Brisbane'), ('Canberra', 'Canberra'), ('Remote', 'Remote')], default='ACT', max_length=50),
        ),
        migrations.CreateModel(
            name='C4CostingSheet',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='c4_costing', serialize=False, to='jobs.jobapplication')),
                ('use_gateway_servegate', models.BooleanField(default=True, help_text='Whether to use gateway service provider', verbose_name='Use SME Gateway/ServeGate?')),
                ('payroll_tax_applicable', models.BooleanField(default=True, help_text='Whether payroll tax applies', verbose_name='Payroll Tax Applicable?')),
                ('management_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Management fee percentage (editable by C4)', max_digits=5, verbose_name='Management Fee (%)')),
                ('payroll_tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('4.85'), help_text='Payroll tax percentage (editable by C4)', max_digits=5, verbose_name='Payroll Tax (%)')),
                ('customer_ceiling_rate_gst_inc', models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Maximum rate chargeable to customer including GST', max_digits=10, verbose_name='Customer Ceiling Rate (GST Inclusive)')),
                ('customer_ceiling_rate_gst_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Customer Ceiling Rate (GST Exclusive)')),
                ('ceiling_rate_saving_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ceiling Rate Saving (%)')),
                ('equipment_cost_gst_inc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Equipment costs for candidate', max_digits=10, verbose_name='Equipment Cost (GST Inclusive)')),
                ('training_memberships_cost_gst_inc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Training and membership costs', max_digits=10, verbose_name='Training/Memberships Cost (GST Inclusive)')),
                ('charge_to_c4_client_gst_inc', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Daily rate charged to C4 client including GST', max_digits=10, verbose_name='Charge to C4 Client (GST Inc)')),
                ('charge_to_c4_client_gst_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Charge to C4 Client (GST Ex)')),
                ('charge_to_c4_client_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GST Amount')),
                ('gateway_fee_gst_inc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gateway/ServeGate Fee (GST Inc)')),
                ('gateway_fee_gst_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gateway/ServeGate Fee (GST Ex)')),
                ('gateway_fee_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gateway Fee GST')),
                ('payroll_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payroll Tax Amount')),
                ('gst_difference_to_ato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Difference in GST to ATO')),
                ('subtotal_payment_to_c4_gst_inc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal Payment to C4 (GST Inc)')),
                ('subtotal_payment_to_c4_gst_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal Payment to C4 (GST Ex)')),
                ('subtotal_payment_to_c4_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal Payment to C4 GST')),
                ('payment_to_service_provider', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Payment to service provider (e.g., Jigsaw)', max_digits=10, verbose_name='Payment to Service Provider')),
                ('net_payment_to_c4_gst_inc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Payment to C4 (GST Inc)')),
                ('net_payment_to_c4_gst_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Payment to C4 (GST Ex)')),
                ('candidate_cost_to_c4_gst_inc', models.DecimalField(blank=True, decimal_places=2, help_text='Includes superannuation', max_digits=10, null=True, verbose_name='Candidate Cost to C4 (GST Inc)')),
                ('candidate_cost_to_c4_gst_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Candidate Cost to C4 (GST Ex)')),
                ('hourly_rate_gst_inc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate (GST Inc)')),
                ('hourly_rate_gst_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate (GST Ex)')),
                ('margin_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Margin ($)')),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Margin (%)')),
                ('project_days', models.PositiveIntegerField(default=230, help_text='Total number of working days for the project', verbose_name='Project Days')),
                ('project_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Project Total Cost')),
                ('travel_costs', models.DecimalField(decimal_places=2, default=Decimal('16500.00'), help_text='Total travel costs for the project', max_digits=12, verbose_name='Travel Costs')),
                ('project_grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Project Grand Total')),
                ('equivalent_annual_package', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Equivalent Annual Package')),
                ('standard_annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Standard Annual Salary')),
                ('superannuation_percentage', models.DecimalField(decimal_places=2, default=Decimal('12.50'), help_text='Superannuation percentage', max_digits=5, verbose_name='Superannuation (%)')),
                ('days_per_week', models.PositiveIntegerField(default=5, verbose_name='Days per Week')),
                ('weekdays_in_year', models.PositiveIntegerField(default=260, verbose_name='Weekdays in Year')),
                ('public_holidays', models.PositiveIntegerField(default=10, verbose_name='Public Holidays')),
                ('annual_leave_days', models.PositiveIntegerField(default=20, verbose_name='Annual Leave Days')),
                ('sick_leave_days', models.PositiveIntegerField(default=5, verbose_name='Sick Leave Days')),
                ('net_days_worked', models.PositiveIntegerField(blank=True, null=True, verbose_name='Net Days Worked')),
                ('manual_override', models.BooleanField(default=False, help_text='Check to prevent auto-calculation', verbose_name='Manual Override')),
                ('calculation_year', models.PositiveIntegerField(default=2024, help_text='Year for calculations', verbose_name='Calculation Year')),
                ('notes', models.TextField(blank=True, help_text='Notes about costing decisions', verbose_name='Costing Notes')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(blank=True, help_text='Last user to update calculations', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_provider', models.ForeignKey(blank=True, help_text='Selected service provider (SME Gateway, ServeGate, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.serviceprovider')),
            ],
            options={
                'verbose_name': 'C4 Costing Sheet',
                'verbose_name_plural': 'C4 Costing Sheets',
            },
        ),
        migrations.DeleteModel(
            name='CostingSheet',
        ),
    ]
