# Generated by Django 5.2.1 on 2025-06-13 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_payrolltaxrate_serviceprovider_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presubmissionassessment',
            name='assessment_template',
            field=models.ForeignKey(blank=True, help_text='Select a template for custom assessment questions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.assessmentquestiontemplate', verbose_name='Assessment Template'),
        ),
        migrations.AlterField(
            model_name='presubmissionassessment',
            name='custom_assessment_data',
            field=models.JSONField(blank=True, default=dict, help_text='Responses to custom assessment questions from selected template', verbose_name='Custom Assessment Responses'),
        ),
    ]
